apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: {{ .Values.users.replicas }}
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: "{{ .Values.image.repository }}/exam-users:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
